name: widgetbook_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.8.0
  widgetbook_annotation: ^3.2.0
  widgetbook_trial:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
